package gal.subtitula.api.transparency.lifecycle;

public enum ProcessingStage {
    QUEUED,
    VALIDATING_UPLOAD,
    SUBMITTING_PROVIDER,
    WAITING_FOR_PROVIDER,
    STORING_PROVIDER_ARTIFACT,
    NORMALIZING_TRANSCRIPT,
    PERSISTING_TRANSCRIPT,
    ALIGNING_AGENDA,
    GENERATING_GUIDE,
    VALIDATING_GUIDE,
    PERSISTING_GUIDE,
    BUILDING_SEARCH_DOCUMENTS,
    GENERATING_EMBEDDINGS,
    PERSISTING_INDEX,
    COMPLETED
}
